# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        uname -a
        GMTSAR=/usr/local/GMTSAR
        GIT=https://github.com/gmtsar/gmtsar
        BRANCH=master

        # prepare system
        sudo apt update
        sudo apt -y upgrade
        sudo apt install -y locales
        # Uncomment en_US.UTF-8 for inclusion in generation
        sudo sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
        # Generate locale
        sudo locale-gen en_US.UTF-8
        # Export env vars
        #sudo echo "export LC_ALL=en_US.UTF-8" >> /root/.bashrc
        #sudo echo "export LANG=en_US.UTF-8" >> /root/.bashrc
        #sudo echo "export LANGUAGE=en_US.UTF-8" >> /root/.bashrc

        # https://github.com/gmtsar/gmtsar/wiki/GMTSAR-Wiki-Page
        sudo apt install -y csh subversion autoconf libtiff5-dev libhdf5-dev wget
        sudo apt install -y liblapack-dev
        sudo apt install -y gfortran
        sudo apt install -y g++
        sudo apt install -y libgmt-dev
        sudo apt install -y gmt-dcw gmt-gshhg
        # gmt-gshhg-full should be installed automatically (it is required to use GMTSAR landmask)
        sudo apt install -y gmt
        # fix for missed "gs" utility and git and make tools
        sudo apt install -y git make
        
    - name: Clone libs
      run: |
        sudo git clone --branch master https://github.com/mobigroup/gmtsar GMTSAR
    - name: Compile libs
      working-directory: GMTSAR
      run: |        
        sudo autoconf
        sudo ./configure --with-orbits-dir=/tmp
        sudo make
        sudo make install
        ls -l ./
        ls -l ./pygmtsar/
        sudo pip install -e ./pygmtsar/
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel h5py netcdf4 h5netcdf \        
          rasterio rioxarray numpy \
          scikit-image scipy sklearn \
          xarray dask distributed zarr nc-time-axis \
          pandas geopandas \
          sentineleof elevation \
          matplotlib seaborn geoviews hvplot datashader bokeh \
          xmltodict joblib tqdm
    
